version: '3'
services:
  
  server:
    container_name: dbwebsvr1-ansible 
    image: ansible-server
    volumes:
      - ${PWD}/.ssh:/root/.ssh/
      - ${PWD}/ansible:/etc/ansible
    links:
      - dbweb1
    ports:
      - "2222:22"
    networks:
      - net 

  dbweb1:
    container_name: dbwebsvr1-dbweb1 
    image: centos-ssh 
    volumes:
      - ${PWD}/.ssh:/root/.ssh/
    networks:
      - net
 
networks:
  net:
